version: '3.7'
services:
  nodejs-api:
    image: jca2323/fiap-mba:microcontainer50aso
    ports:
      - "3081:3081"
    container_name: nodejs-api
    links:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db